# -*- coding: utf-8 -*-
"""task4_visualization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNPAcMuEGkz39ZqLuTnEQPzvM25sODGG
"""

# task4_visualization.py
# TrendPulse - Task 4: Visualizations

import pandas as pd
import matplotlib.pyplot as plt
import os

# Step 1: Setup
csv_file = "data/trends_analysed.csv"
if not os.path.exists(csv_file):
    raise FileNotFoundError("Analysed CSV file not found. Run Task 3 first.")

df = pd.read_csv(csv_file)

# Create outputs folder if not exists
if not os.path.exists("outputs"):
    os.makedirs("outputs")

# Step 2: Chart 1 — Top 10 Stories by Score
top10 = df.nlargest(10, "score")[["title", "score"]]
# Shorten titles > 50 chars
top10["title"] = top10["title"].apply(lambda x: x[:47] + "..." if len(x) > 50 else x)

plt.figure(figsize=(10,6))
plt.barh(top10["title"], top10["score"], color="skyblue")
plt.xlabel("Score")
plt.ylabel("Story Title")
plt.title("Top 10 Stories by Score")
plt.gca().invert_yaxis()  # highest score at top
plt.tight_layout()
plt.savefig("outputs/chart1_top_stories.png")
plt.close()

# Step 3: Chart 2 — Stories per Category
category_counts = df["category"].value_counts()

plt.figure(figsize=(8,6))
category_counts.plot(kind="bar", color=["#FF9999","#66B2FF","#99FF99","#FFCC99","#C299FF"])
plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")
plt.tight_layout()
plt.savefig("outputs/chart2_categories.png")
plt.close()

# Step 4: Chart 3 — Score vs Comments Scatter
plt.figure(figsize=(8,6))
colors = df["is_popular"].map({True: "green", False: "red"})
plt.scatter(df["score"], df["num_comments"], c=colors, alpha=0.6)
plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")
plt.legend(handles=[
    plt.Line2D([0],[0], marker='o', color='w', label='Popular', markerfacecolor='green', markersize=8),
    plt.Line2D([0],[0], marker='o', color='w', label='Not Popular', markerfacecolor='red', markersize=8)
])
plt.tight_layout()
plt.savefig("outputs/chart3_scatter.png")
plt.close()

# Bonus: Dashboard combining all charts
fig, axes = plt.subplots(1, 3, figsize=(20,6))

# Chart 1 in dashboard
axes[0].barh(top10["title"], top10["score"], color="skyblue")
axes[0].set_title("Top 10 Stories by Score")
axes[0].set_xlabel("Score")
axes[0].invert_yaxis()

# Chart 2 in dashboard
axes[1].bar(category_counts.index, category_counts.values, color=["#FF9999","#66B2FF","#99FF99","#FFCC99","#C299FF"])
axes[1].set_title("Stories per Category")
axes[1].set_xlabel("Category")
axes[1].set_ylabel("Count")

# Chart 3 in dashboard
axes[2].scatter(df["score"], df["num_comments"], c=colors, alpha=0.6)
axes[2].set_title("Score vs Comments")
axes[2].set_xlabel("Score")
axes[2].set_ylabel("Comments")

fig.suptitle("TrendPulse Dashboard", fontsize=16)
plt.tight_layout()
plt.savefig("outputs/dashboard.png")
plt.close()

print("Charts saved in outputs/ folder:")
print(" - chart1_top_stories.png")
print(" - chart2_categories.png")
print(" - chart3_scatter.png")
print(" - dashboard.png (bonus)")