# -*- coding: utf-8 -*-
"""task2_data_processing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--zcTb9RlFY0mIESNRGK8KlfCjXpVLcr
"""

# task2_data_processing.py
# TrendPulse - Task 2: Data Processing

import pandas as pd
import os
import json

# Step 1: Load JSON file
# Find the latest trends JSON file in data/ folder
json_files = [f for f in os.listdir("data") if f.startswith("trends_") and f.endswith(".json")]
if not json_files:
    raise FileNotFoundError("No trends JSON file found in data/ folder.")

latest_file = sorted(json_files)[-1]  # pick the latest by filename
print(f"Loading {latest_file}...")

df = pd.read_json(os.path.join("data", latest_file))
print(f"Loaded {len(df)} stories from {latest_file}")

# Step 2: Clean the Data

# Remove duplicates by post_id
df = df.drop_duplicates(subset="post_id")
print(f"After removing duplicates: {len(df)}")

# Drop rows with missing critical fields
df = df.dropna(subset=["post_id", "title", "score"])
print(f"After removing nulls: {len(df)}")

# Ensure score and num_comments are integers
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].fillna(0).astype(int)

# Remove low-quality stories (score < 5)
df = df[df["score"] >= 5]
print(f"After removing low scores: {len(df)}")

# Strip whitespace from titles
df["title"] = df["title"].str.strip()

# Step 3: Save as CSV
output_file = "data/trends_clean.csv"
df.to_csv(output_file, index=False)
print(f"Saved {len(df)} rows to {output_file}")

# Print summary: stories per category
summary = df["category"].value_counts()
print("\nStories per category:")
print(summary)