# -*- coding: utf-8 -*-
"""task3_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCQF_wu54UJO7PG28xNotw--PTuvD_Ix
"""

# task3_analysis.py
# TrendPulse - Task 3: Analysis with Pandas & NumPy

import pandas as pd
import numpy as np
import os

# Step 1: Load and Explore
csv_file = "data/trends_clean.csv"
if not os.path.exists(csv_file):
    raise FileNotFoundError("Clean CSV file not found. Run Task 2 first.")

df = pd.read_csv(csv_file)
print(f"Loaded data: {df.shape}\n")

print("First 5 rows:")
print(df.head())

# Average score and comments
avg_score = df["score"].mean()
avg_comments = df["num_comments"].mean()
print(f"\nAverage score   : {avg_score:.2f}")
print(f"Average comments: {avg_comments:.2f}")

# Step 2: Basic Analysis with NumPy
scores = df["score"].values
comments = df["num_comments"].values

print("\n--- NumPy Stats ---")
print(f"Mean score   : {np.mean(scores):.2f}")
print(f"Median score : {np.median(scores):.2f}")
print(f"Std deviation: {np.std(scores):.2f}")
print(f"Max score    : {np.max(scores)}")
print(f"Min score    : {np.min(scores)}")

# Category with most stories
most_category = df["category"].value_counts().idxmax()
most_count = df["category"].value_counts().max()
print(f"\nMost stories in: {most_category} ({most_count} stories)")

# Story with most comments
max_comments_idx = np.argmax(comments)
print(f"Most commented story: \"{df.iloc[max_comments_idx]['title']}\" — {df.iloc[max_comments_idx]['num_comments']} comments")

# Step 3: Add New Columns
df["engagement"] = df["num_comments"] / (df["score"] + 1)
df["is_popular"] = df["score"] > avg_score

# Step 4: Save the Result
output_file = "data/trends_analysed.csv"
df.to_csv(output_file, index=False)
print(f"\nSaved to {output_file}")