# -*- coding: utf-8 -*-
"""task1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kQ4aA-Gjm-l1zfD1VQlSl2V0Hj_eEFx
"""

# task1_data_collection.py
# TrendPulse - Task 1: Data Collection

import requests
import time
import os
import json
from datetime import datetime

# Define headers for API requests
headers = {"User-Agent": "TrendPulse/1.0"}

# Define categories and keywords
categories = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "API", "GPU", "LLM"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["NFL", "NBA", "FIFA", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "NASA", "genome"],
    "entertainment": ["movie", "film", "music", "Netflix", "game", "book", "show", "award", "streaming"]
}

# Step 1: Fetch top story IDs
try:
    top_ids = requests.get("https://hacker-news.firebaseio.com/v0/topstories.json", headers=headers).json()
except Exception as e:
    print("Error fetching top stories:", e)
    top_ids = []

# Limit to first 500 IDs
top_ids = top_ids[:500]

# Function to assign category based on title
def assign_category(title):
    if not title:
        return None
    title_lower = title.lower()
    for cat, keywords in categories.items():
        for kw in keywords:
            if kw.lower() in title_lower:
                return cat
    return None

# Step 2: Fetch story details and categorize
collected = []
for cat in categories.keys():
    count = 0
    for story_id in top_ids:
        if count >= 25:  # limit per category
            break
        try:
            story = requests.get(f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json", headers=headers).json()
            if not story or "title" not in story:
                continue
            category = assign_category(story.get("title"))
            if category == cat:
                collected.append({
                    "post_id": story.get("id"),
                    "title": story.get("title"),
                    "category": category,
                    "score": story.get("score"),
                    "num_comments": story.get("descendants"),
                    "author": story.get("by"),
                    "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                })
                count += 1
        except Exception as e:
            print(f"Error fetching story {story_id}: {e}")
            continue
    # Sleep 2 seconds between categories
    time.sleep(2)

# Step 3: Save to JSON file
if not os.path.exists("data"):
    os.makedirs("data")

filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"
with open(filename, "w", encoding="utf-8") as f:
    json.dump(collected, f, indent=2)

print(f"Collected {len(collected)} stories. Saved to {filename}")

